### ISSUE TITLE
When will it release the updated version?

### ISSUE THREAD

**Issue by HelenMao** [elvisyjlin/RelGAN-PyTorch#6]
Hi, I am reproducing the results of celebA and celebA-HQ using this repo. However, I find the results are very bad.
In another issue, I find you said you were still working on this repo, could you tell me when will it release the updated version? Thanks!

**Comment by HelenMao** [comment]
I think the problem lies in
` vec_ab = att_a - att_b
    vec_ac = att_a - att_c
    vec_cb = att_c - att_b`
should be
` vec_ab = att_b - att_a
    vec_ac = att_c - att_a
    vec_cb = att_b - att_c`

**Comment by EvaFlower** [comment]
@HelenMao 
Hi, did you get good results after the revision?
Thanks.
